aaconst countries = [
  {name:"Afghanistan", code:"+93", flag:"🇦🇫"},
  {name:"Afrique du Sud", code:"+27", flag:"🇿🇦"},
  {name:"Albanie", code:"+355", flag:"🇦🇱"},
  {name:"Algérie", code:"+213", flag:"🇩🇿"},
  {name:"Allemagne", code:"+49", flag:"🇩🇪"},
  {name:"Andorre", code:"+376", flag:"🇦🇩"},
  {name:"Angola", code:"+244", flag:"🇦🇴"},
  {name:"Arabie Saoudite", code:"+966", flag:"🇸🇦"},
  {name:"Argentine", code:"+54", flag:"🇦🇷"},
  {name:"Australie", code:"+61", flag:"🇦🇺"},
  {name:"Autriche", code:"+43", flag:"🇦🇹"},
  {name:"Belgique", code:"+32", flag:"🇧🇪"},
  {name:"Bénin", code:"+229", flag:"🇧🇯"},
  {name:"Brésil", code:"+55", flag:"🇧🇷"},
  {name:"Burkina Faso", code:"+226", flag:"🇧🇫"},
  {name:"Burundi", code:"+257", flag:"🇧🇮"},
  {name:"Cameroun", code:"+237", flag:"🇨🇲"},
  {name:"Canada", code:"+1", flag:"🇨🇦"},
  {name:"Chili", code:"+56", flag:"🇨🇱"},
  {name:"Chine", code:"+86", flag:"🇨🇳"},
  {name:"Colombie", code:"+57", flag:"🇨🇴"},
  {name:"Congo", code:"+242", flag:"🇨🇬"},
  {name:"Côte d’Ivoire", code:"+225", flag:"🇨🇮"},
  {name:"Danemark", code:"+45", flag:"🇩🇰"},
  {name:"Égypte", code:"+20", flag:"🇪🇬"},
  {name:"Espagne", code:"+34", flag:"🇪🇸"},
  {name:"États-Unis", code:"+1", flag:"🇺🇸"},
  {name:"France", code:"+33", flag:"🇫🇷"},
  {name:"Gabon", code:"+241", flag:"🇬🇦"},
  {name:"Ghana", code:"+233", flag:"🇬🇭"},
  {name:"Grèce", code:"+30", flag:"🇬🇷"},
  {name:"Inde", code:"+91", flag:"🇮🇳"},
  {name:"Indonésie", code:"+62", flag:"🇮🇩"},
  {name:"Italie", code:"+39", flag:"🇮🇹"},
  {name:"Japon", code:"+81", flag:"🇯🇵"},
  {name:"Kenya", code:"+254", flag:"🇰🇪"},
  {name:"Maroc", code:"+212", flag:"🇲🇦"},
  {name:"Mexique", code:"+52", flag:"🇲🇽"},
  {name:"Nigéria", code:"+234", flag:"🇳🇬"},
  {name:"Norvège", code:"+47", flag:"🇳🇴"},
  {name:"Pays-Bas", code:"+31", flag:"🇳🇱"},
  {name:"Portugal", code:"+351", flag:"🇵🇹"},
  {name:"Royaume-Uni", code:"+44", flag:"🇬🇧"},
  {name:"Russie", code:"+7", flag:"🇷🇺"},
  {name:"Sénégal", code:"+221", flag:"🇸🇳"},
  {name:"Suisse", code:"+41", flag:"🇨🇭"},
  {name:"Tunisie", code:"+216", flag:"🇹🇳"},
  {name:"Turquie", code:"+90", flag:"🇹🇷"},
  {name:"Ukraine", code:"+380", flag:"🇺🇦"},
  {name:"Zambie", code:"+260", flag:"🇿🇲"},
  {name:"Zimbabwe", code:"+263", flag:"🇿🇼"}
];
